{
 "title": "Project-DevOps",
 "time": { "from": "2025-07-05T17:32:29.600Z", "to": "2025-07-05T17:38:50.419Z" },
 "panels": [
  {
   "title": "Status Code HTTP table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  target,\r\n  value2 AS status_code,\r\n  COUNT(*) AS total\r\nFROM http_results\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY target, value2\r\nORDER BY total DESC"
    }
   ]
  },
  {
   "title": "Load Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  target,\r\n  value1 AS load_time\r\nFROM http_results\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  target,\r\n  value2 AS packet_loss\r\nFROM ping_results\r\nWHERE $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Gráfico de RTT ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  target,\r\n  value1 AS rtt\r\nFROM ping_results\r\nWHERE $__timeFilter(timestamp)"
    }
   ]
  }
 ]
}