{
 "title": "Viaipe Data",
 "time": { "from": "2025-07-05T20:19:03.997Z", "to": "2025-07-05T20:19:04.004Z" },
 "panels": [
  {
   "title": "Connection quality per client over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  cliente,\r\n  qualidade\r\nFROM\r\n  viaipe_stats\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nORDER BY\r\n  time\r\n"
    }
   ]
  },
  {
   "title": "Bandwidth consumption per client over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  cliente,\r\n  banda_consumo\r\nFROM\r\n  viaipe_stats\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nORDER BY\r\n  time"
    }
   ]
  },
  {
   "title": "Average avaiability per client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  cliente,\r\n  ROUND(AVG(disponibilidade)::numeric, 2) AS disponibilidade_media\r\nFROM\r\n  viaipe_stats\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY\r\n  time, cliente\r\nORDER BY\r\n  time, cliente\r\n"
    }
   ]
  }
 ]
}